import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn,execFileSync} from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import {fileURLToPath} from 'node:url';
import {backup,DatabaseSync} from 'node:sqlite';
import backups from '../shared/database-backup.cjs';
process.chdir(fileURLToPath(new URL('..', import.meta.url)));
const require=createRequire(new URL('../backend/package.json',import.meta.url));
require('reflect-metadata');
const {NestFactory}=require('@nestjs/core');
const {AppModule}=require('../backend/dist/app.module.js');
const {configureApplication}=require('../backend/dist/runtime-config.js');
const {AuthService}=require('../backend/dist/account/auth.service.js');
const {DatabaseService}=require('../backend/dist/account/database.service.js');
const {InvoiceHistoryService}=require('../backend/dist/invoice/invoice-history.service.js');
const puppeteer=require('puppeteer').default;
Object.assign(process.env,{DATABASE_PATH:':memory:',SMTP_HOST:'',APP_ENV:'production',APP_ORIGIN:'https://invoices.example.test',COOKIE_SECURE:'true',TRUST_PROXY:'true',REGISTRATION_ENABLED:'false'});
const app=await NestFactory.create(AppModule,{logger:false});
configureApplication(app);
await app.listen(0,'127.0.0.1');
const origin=await app.getUrl();
const scratch=await fs.mkdtemp(path.join(os.tmpdir(),'invoice-deployment-'));
await fs.chmod(scratch,0o700);
const processes=[];
let browser;
let appClosed=false;
async function frontend(trusted) {
  const child=spawn(process.execPath,['frontend/server.mjs'],{env:{...process.env,PORT:'0',BACKEND_URL:origin,TRUST_CLOUDFLARE_PROXY:String(trusted)},stdio:['ignore','pipe','pipe']});
  processes.push(child);
  let output='';
  return new Promise((resolve,reject) => {
    const timer=setTimeout(()=>reject(new Error('Frontend startup timeout')),10000);
    child.once('exit',code=>{clearTimeout(timer);reject(new Error(`Frontend exited ${code}`))});
    child.stderr.on('data',buffer=>process.stderr.write(buffer));
    child.stdout.on('data',buffer=>{output+=buffer;const match=output.match(/listening on port (\d+)/);if(match){clearTimeout(timer);resolve(`http://127.0.0.1:${match[1]}`)}});
  });
}
try {
  const auth=app.get(AuthService);
  const user=await auth.register({email:'existing@example.invalid',password:'disposable-account-password'});
  const history=app.get(InvoiceHistoryService);
  const invoice={invoiceNumber:'SF 44',invoiceDate:'2026-09-30',paymentTerm:'2026-10-30',seller:{name:'Seller',address:'',individualActivity:'',taxNumber:'',bankName:'',swift:'',iban:''},buyer:{name:'Buyer',address:'',vatCode:''},items:[{description:'Work',quantity:20,unit:'d',price:100}],additionalComment:'Retained'};
  const id=history.save(user.id,invoice,Buffer.from('original-invoice-zip'));
  history.update(user.id,id,0,{...invoice,additionalComment:'Edited'},Buffer.from('edited-invoice-zip'),'deployment-edit-0001','fingerprint');
  const url=await frontend(true);
  const headers={'Content-Type':'application/json','X-Invoice-Client':'web',Origin:process.env.APP_ORIGIN,'CF-Connecting-IP':'203.0.113.50','X-Forwarded-For':'attacker-forged-chain'};
  const config=await fetch(url+'/api/auth/config');
  assert.deepEqual(await config.json(),{registrationEnabled:false});
  assert.ok(config.headers.get('cache-control').includes('no-store'));
  assert.equal(config.headers.get('cloudflare-cdn-cache-control'),'no-store');
  assert.equal((await fetch(url+'/api/auth/register',{method:'POST',headers,body:JSON.stringify({email:'blocked@example.invalid',password:'disposable-password'})})).status,403);
  for (const forbidden of ['https://other.example.test','null']) {
    assert.equal((await fetch(url+'/api/auth/login',{method:'POST',headers:{...headers,Origin:forbidden,'Sec-Fetch-Site':'same-site'},body:'{}'})).status,403);
  }
  const login=await fetch(url+'/api/auth/login',{method:'POST',headers,body:JSON.stringify({email:user.email,password:'disposable-account-password'})});
  assert.equal(login.status,201);
  const setCookie=login.headers.get('set-cookie');
  for (const flag of ['Secure','HttpOnly','SameSite=Lax']) assert.ok(setCookie.includes(flag));
  const cookie=setCookie.split(';')[0];
  const versions=await fetch(url+`/invoice/history/${id}/versions`,{headers:{Cookie:cookie}});
  assert.deepEqual((await versions.json()).versions.map(v=>v.revision),[1,0]);
  const oldFiles=await fetch(url+`/invoice/history/${id}/versions/0/download`,{headers:{Cookie:cookie}});
  assert.equal(Buffer.from(await oldFiles.arrayBuffer()).toString(),'original-invoice-zip');
  const updated=await fetch(url+'/api/preferences',{method:'PUT',headers:{...headers,Cookie:cookie},body:JSON.stringify({savedItems:['Overtime']})});
  assert.equal(updated.status,200);
  assert.ok((await updated.json()).savedItems.includes('Overtime'));
  const anonymous=await fetch(url+`/invoice/history/${id}/versions`);
  assert.equal(anonymous.status,401);assert.ok(anonymous.headers.get('cache-control').includes('no-store'));
  const limitedHeaders={...headers,'CF-Connecting-IP':'203.0.113.70'};
  for(let n=0;n<30;n++) assert.equal((await fetch(url+'/api/auth/login',{method:'POST',headers:limitedHeaders,body:'{}'})).status,400);
  assert.equal((await fetch(url+'/api/auth/login',{method:'POST',headers:limitedHeaders,body:'{}'})).status,429);
  assert.equal((await fetch(url+'/api/auth/login',{method:'POST',headers:{...limitedHeaders,'CF-Connecting-IP':'203.0.113.71'},body:'{}'})).status,400);
  const untrustedUrl=await frontend(false);
  for(let n=0;n<30;n++) assert.equal((await fetch(untrustedUrl+'/api/auth/login',{method:'POST',headers:{...headers,'CF-Connecting-IP':`203.0.113.${n}`},body:'{}'})).status,400);
  assert.equal((await fetch(untrustedUrl+'/api/auth/login',{method:'POST',headers:{...headers,'CF-Connecting-IP':'203.0.113.99'},body:'{}'})).status,429,'Untrusted client IP headers must not reset the rate limit');
  const source=path.join(scratch,'source.sqlite');
  await fs.writeFile(source,'',{mode:0o600});
  await backup(app.get(DatabaseService).db,source);
  const snapshot=await backups.runBackup({source,directory:path.join(scratch,'backups'),force:true});
  const restored=path.join(scratch,'new-server','invoices.sqlite');
  execFileSync(process.execPath,['scripts/restore-database.mjs',snapshot.file,restored],{stdio:['ignore','pipe','pipe']});
  const copy=new DatabaseSync(restored,{readOnly:true});
  assert.equal(copy.prepare('SELECT COUNT(*) AS n FROM users').get().n,1);
  assert.equal(copy.prepare('SELECT COUNT(*) AS n FROM invoice_versions').get().n,2);
  assert.equal(Buffer.from(copy.prepare('SELECT zip FROM invoice_versions WHERE revision=0').get().zip).toString(),'original-invoice-zip');
  assert.ok(JSON.parse(copy.prepare('SELECT preferences FROM users').get().preferences).savedItems.includes('Overtime'));
  copy.close();
  const before=await fs.readFile(restored);
  assert.throws(()=>execFileSync(process.execPath,['scripts/restore-database.mjs',snapshot.file,restored],{stdio:['ignore','pipe','pipe']}));
  assert.deepEqual(await fs.readFile(restored),before,'Restore must never overwrite an existing database');
  browser=await puppeteer.launch({headless:true});
  const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url,{waitUntil:'networkidle0'});
  await page.waitForSelector('#auth-email');
  assert.equal(await page.$('.auth-switch'),null);
  assert.ok((await page.$eval('.auth-card',e=>e.innerText)).includes('Sign in'));
  assert.deepEqual(errors,[]);
  await app.close();
  appClosed=true;
  const unavailable=await fetch(url+'/api/auth/me');
  assert.equal(unavailable.status,502);
  assert.ok((await unavailable.json()).message.includes('temporarily unavailable'));
  assert.ok(unavailable.headers.get('cache-control').includes('no-store'));
  console.log(JSON.stringify({closedRegistration:true,existingLogin:true,secureCookies:true,strictOrigins:true,clientIpLimits:true,forwardedSpoofingRejected:true,privateCaching:true,retainedVersionDownload:true,verifiedDatabaseRestore:true,existingDatabaseProtected:true,loginUI:true,browserErrors:errors,proxyFailureHandled:true}));
} finally {
  if(browser) await browser.close();
  for(const child of processes) {if(child.exitCode===null){const exited=once(child,'exit');child.kill('SIGTERM');await exited;}}
  if(!appClosed) await app.close();
  await fs.rm(scratch,{recursive:true,force:true});
}
